# -*- coding: utf-8 -*-
"""Zonas de briga.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1emnyN6ngmFaeHUNUNdrgWxwPOeWbxSfK
"""

import pandas as pd, numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
from google.colab import drive
drive.mount('/content/drive')

caminho=('/content/drive/My Drive/trade/temporeal.csv')
data = pd.read_csv(caminho,index_col=None)
data.columns=['Preço']
data

zonas=data.groupby(["Preço"])['Preço'].count().sort_values(ascending=False).iloc[0:45].plot(kind='bar',figsize=(30,30),title="Zonas de briga")

zonas2=data.groupby('Preço')


zonas

alvos=data.groupby(["Preço"])['Preço'].count().sort_values(ascending=False).iloc[0:30]

alvos

# Commented out IPython magic to ensure Python compatibility.
tt=pd.DataFrame(alvos)



import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation



overdoses = pd.read_csv(caminho)
def get_data(table,rownum,title):
    data = pd.DataFrame(table.loc[rownum][2:]).astype(float)

    data.columns = {title}
    return data


# %matplotlib notebook
title = 'Heroin Overdoses'


overdose = pd.DataFrame(overdoses)
#XN,YN = augment(x,y,10)
#augmented = pd.DataFrame(YN,XN)
overdose.columns = {title}


Writer = animation.writers['ffmpeg']
writer = Writer(fps=20, metadata=dict(artist='Me'), bitrate=1800)



fig = plt.figure(figsize=(10,6))
plt.xlim(1999, 2016)
plt.ylim(np.min(overdose)[0], np.max(overdose)[0])
plt.xlabel('Year',fontsize=20)
plt.ylabel(title,fontsize=20)
plt.title('Heroin Overdoses per Year',fontsize=20)



def animate(i):
    data = overdose.iloc[:int(i+1)] #select data range
    p = sns.lineplot(x=data.index, y=data[title], data=data, color="r")
    p.tick_params(labelsize=17)
    plt.setp(p.lines,linewidth=7)


ani = matplotlib.animation.FuncAnimation(fig, animate, frames=17, repeat=True)
